In [27]:
import numpy as np
A=np.array([[-3,-5],[2,-1]])
#The square of this matrix using built-in functions is
A@A
np.dot(A,A)

array([[-1, 20],
       [-8, -9]])

In [28]:
#The square of this matirx using loops is
A_square = np.zeros((2,2))
for i in range(len(A)):
    for j in range(len(A)):
        for k in range(len(A)):
            A_square[i][j] += A[i][k]*A[k][j]
A_square

array([[-1., 20.],
       [-8., -9.]])

In [33]:
#The square of the square of this matrix using built-in functions is
A@A@A@A
np.dot(A,np.dot(A,np.dot(A,A)))

array([[-159, -200],
       [  80,  -79]])

In [34]:
#The square of the square of this matirx using loops is
A_square_square = np.zeros((2,2))
for i in range(len(A)):  
    for j in range(len(A)):
        for k in range(len(A)):  
            for l in range(len(A)): 
                for m in range(len(A)):
                    A_square_square[i][j] += A[i][k]*A[k][l]*A[l][m]*A[m][j]
A_square_square

array([[-159., -200.],
       [  80.,  -79.]])